all:
	syclcc himeno_sycl.cpp -O3 -DSSMALL -o himeno_ssmall
	syclcc himeno_sycl.cpp -O3 -DSMALL -o himeno_small
	syclcc himeno_sycl.cpp -O3 -DMIDDLE -o himeno_middle
	syclcc himeno_sycl.cpp -O3 -DLARGE -o himeno_large
	syclcc himeno_sycl.cpp -O3 -DELARGE -o himeno_elarge
